obstacle_range: 100
raytrace_range: 100
# footprint: [[x0, y0], [x1, y1], ... [xn, yn]]
robot_radius: 0.2
inflation_radius: 0.6

observation_sources: laser_scan_sensor

laser_scan_sensor: {sensor_frame: lidar_link, data_type: LaserScan, topic: /scan, marking: true, clearing: true}
